### ISSUE TITLE
Vimcom not loading (Mac OS X)

### ISSUE THREAD

**Issue by idurandiaz** [jalvesaq/VimCom#28]
I am new to R, but I have been using Vim for sometime. I installed vim-r-plugin, I tried to follow all the instructions, and it is loading from vim in the terminal and MacVim as well (after \rf R console opens up and I can send commands from Vim to R with \d or \q without issues). However, after \rf it gives me a message that vimcom was not loaded yet (in both the terminal and MacVim) and therefore when I try to do omni-completion nothing shows in the list (it actually asks whether vimcom was loaded). I also have YouCompleteMe installed and I thought that was the issue initially but even after disabling it the issue still  persists.

Just want to know if vimcom is supposed to load and work in MacVim (therefore omni-completion), and if yes then how can I potentially solve the problem. Thanks!, and great plugin btw.

**Comment by jalvesaq** [comment]
If vimcom was compiled and installed correctly, you should just put in your .Rprofile:

```r
if(interactive()){
    options(vimcom.verbose = 1)
    library(vimcom)
}

However, I suggest that you try [Nvim-R] and [nvimcom] instead.

[Nvim-R]: https://github.com/jalvesaq/Nvim-R
[nvimcom]: https://github.com/jalvesaq/nvimcom

**Comment by iDurandi** [comment]
Thanks for the reply,

I realized that X11 was not installed properly so that was causing the problem. Now vimcom is loading from both MacVim and and Terminal without issues.

**However**, the plugin is not working if I start vim in Tmux. Even if I start with vim `--servername VIM`, I keep getting the same message that Vim has to be restarted with --servername. I also added alias `vim='vim --servername VIM'` to my `~/.bashrc` and my `~/.tmux.conf` looks the same as what you suggested in the documentation, as well as my `~/.Rprofile`.

In any case I'm quite happy with the setup so far in MacVim and the terminal. I will give it a try to Neovim though.

**Comment by jalvesaq** [comment]
Are you using the Vim (terminal application) that comes with MacVim? It does not have the server feature. It only has the client feature. Vimcom uses it to send messages to MacVim, but it cannot receive messages from R.

or

Did you build Vim yourself? Did you compile it with X11 support?

**Comment by jalvesaq** [comment]
Neovim does not require X11. The communication between Neovim and R goes through the same channels in Linux, Windows and Mac OS X.

**Comment by iDurandi** [comment]
Yes I am using the Vim in terminal that comes with MacVim. Should I build it myself (with home-brew for example?) with X11 support then?

I want to give Neovim a try, I just don't know how easy it will be the transition from Vim to Neovim, like how compatible my .vimrc will be in Neovim and if I can use Vundle for example to manage my plugins and all that...

**Comment by jalvesaq** [comment]
If you want to use Vim in the terminal, you have to build Vim with 'clientserver' support (X11).

I use the same vimrc and the same plugins with both Vim and Neovim. Vundle works, but I am now using vim-plug.

**Comment by iDurandi** [comment]
Yes I checked in Vim with `:version` and it is built with `+clientserver`. When I launch vim in tmux I still get the same message to load Vim again with `--servername VIM`, but I just ignore that message and it seems that the plugin is working without issues (vimcom, omni-completion, sending lines to R with `space bar` or `\q`, etc.). So it is working for me without issues anymore (just this message at the beginning which can be easily ignored).

I also installed the Nvim-R plugin and it is working perfectly as well. I just feel a bit more confortable using the terminal pane with R in Tmux that the buffer window with R in Nvim, but I guess it is just a matter of getting used to it (typing in the buffer with R in Nvim is still kind of new to me, maybe I just have to read Nvim's documentation).

Thanks a lot for the great plugins!

**Comment by jalvesaq** [comment]
The Vim application that comes with MacVim says that it has the `+clientserver` feature, but the truth is that it has only *client* side of the feature. Please, compare Vim, MacVim and Neovim when you send the first of the following lines to R:

```r
library(foreign)
read.spss()
```

In both MacVim and Neovim `read.spss` should be automatically highlighted as a function (in MacVim you may have to move the cursor to update the highlighting).

Also, try to run the object browser with `<LocalLeader>ro` and see what happens when you create new objects in the R Console.

At first, it was a bit strange to me to use R in Neovim buffer too. But now I only use it this way. The plugin's documentation has some tips (`:h R_in_buffer`). If you really want to run R inside Tmux, please, read `:h Nvim-R-Tmux`.

**Comment by iDurandi** [comment]
**In Vim**:
No color of read.spss() and in the R console got the following message:

`> read.spss()
Error in grep("^(http|ftp|https)://", file) : 
  argument "file" is missing, with no default`

When launching \ro, i get this message:
`The Object Browser will not be automatically updated because Vim's client/server was not started.`

So after creating objects in R, nothing happens in the object browser.

**In Macvim**

read.spss() is colored and in R console got the same message as in vim.

When launching \ro I get no error message, but then if I pass objects to R I’m not sure what am I suppose to expect, as I am not seeing any change in the object browser (I passed several objects and only x<-5 showed in the list without value).

**In Nvim**

read.spss() is colored and in R console got the same message as in vim and macvim.

When launching \ro I get no error and when passing objects to R (e.g `x <- 5`) then I see that the objects appear in the object browser (no the value assigned to it) as I pass them (so it is updating properly I would say), but values of objects don't show as in RStudio for example.

Also, in Nvim i can’t used \d or \q (only the space bar) to pass lines to R, is there any configuration I am missing?

You are right, I am getting used to Nvim buffer now, so probably will be my choice for running R.

**Comment by jalvesaq** [comment]
Sorry, I did not explain well. The command `read.spss` was not supposed to be sent to R Console. My goal was just to show that it would be highlighted as soon as the `foreign` library was loaded.

If the Object Browser is not working properly in MacVim, this is a bug, but I can't fix it because I don't have access to Mac. I only have had access to one for a couple of weeks in January. As I have told, the communication between Neovim and R use the same channels in Linux, Windows and Mac OS X. So, it is less likely that I will break something for Mac OS X while developing Nvim-R on Linux (and testing on Windows) than while developing Vim-R.

The values do not show in the Object Browser. The colors indicate the type of object, and you can type `\rs`, `\rt`, `\ra`, `\rh`, etc over them to get information about them in the R Console. You can also see the elements of lists by pressing `<Enter>` over them.

When you map `<Space>` to `<Plug>RDSendLine`, `<LocalLeader>d` is no longer mapped. You should get the same results in Vim and Neovim.

In Vim-R, the default value of `vimrplugin_insert_mode_cmds` is `1`, but in Nvim-R the default value of `R_insert_mode_cmds` is `0`. Please, see `:h R_insert_mode_cmds` (I have just fixed the documentation about this option: https://github.com/jalvesaq/Nvim-R/commit/3312e77fcd11601e75586017029d1b5013ef80aa).

**Comment by iDurandi** [comment]
I think everything is working as expected in Mac, so I am using Nvim now.

I am also running both plugins (vim and nvim R) in my linux (Ubuntu) machine. Vim-R pluging works very well and the object browser updates as well after passing objects to R. Nvim on the other hand is not working very well for some reason. I ln -s my .vim folder and .vimrc as in Mac, and it is loading all of my configurations of my .vimrc, but for some reason it is not coloring any the code like Vim in any file (.py, .tex, .R, etc.), all text is just plain white. I installed the Nvim-R plugin and it loads without issues after \rf. Then I open the object browser (\ro) and when first passing an object to R, I get the following message:

` Error detected while processing function ROnJobStdout:                               
line    7:`
`E117: Unknown function: FillRLibList`

I press enter and then the object is passed to R and after that the message doesn't show again. The object browser is updated right away but is it not colored either (plain white) and the objects have a `{#` in front. 

Since I installed the plug-in right after installing Nvim in Linux, I am not sure if Nvim was not coloring the code since the beginning, but I think it might have happened after the first time I got the above message. Do you think it is related?

**Comment by jalvesaq** [comment]
The message means that the file `R/functions.vim` has not being sourced yet. Did you follow the instructions from `:h nvim-from-vim`? The most important difference is that the `~/.vim` directory and the `~/.vimrc` configuration file have other locations:

```
~/.config/nvim
~/.config/nvim/init.vim
```

**Comment by iDurandi** [comment]
Yes I followed the `nvim-from-vim`... I just reinstalled Nvim and added `syntax enable` to my .vimrc and everything is working fine now, I am not getting the error message anymore when passing objects to R. Also the object browser is updating automatically. So thanks for the help, both Mac and Linux versions are working well for me.

**Comment by jalvesaq** [comment]
Thanks for the feedback! We may let this issue open, since the solution to vimcom problems was the migration to another software.

**Comment by iDurandi** [comment]
Sure, thanks again!

**Comment by jalvesaq** [comment]
This will be fixed by (although not tested on Mac OS X):
https://github.com/jcfaria/Vim-R-plugin/tree/jobchannel
https://github.com/jalvesaq/VimCom/tree/jobchannel

**Comment by jalvesaq** [comment]
This issue should be fixed now.
